version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py loaddata checks/fixtures/data.json && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - wkhtmltopdf
      - celery
      - flower
    volumes:
      - .:/app
      - media:/app/media

  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: 'redis:6.2.8'
    ports:
      - "6379:6379"

  wkhtmltopdf:
    image: 'openlabs/docker-wkhtmltopdf-aas:latest'

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app checks worker --loglevel info
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - wkhtmltopdf
    volumes:
      - media:/app/media

  flower:
    image: 'mher/flower:2.0'
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - celery

volumes:
  pgdata:
  media: