# Generated by Django 4.2.3 on 2023-07-18 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'merchant point',
                'verbose_name_plural': 'merchant points',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('api_key', models.CharField(default=uuid.uuid4, unique=True, verbose_name='API access key')),
                ('check_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=10, verbose_name='Type of check')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated date')),
                ('merchant_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checks.merchantpoint', verbose_name='Merchant point')),
            ],
            options={
                'verbose_name': 'printer',
                'verbose_name_plural': 'printers',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=10, verbose_name='Type of check')),
                ('order', models.JSONField(verbose_name='Order data')),
                ('status', models.CharField(choices=[('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')], default='new', max_length=10, verbose_name='Status of check')),
                ('pdf_file', models.FileField(null=True, upload_to='', verbose_name='PDF file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checks.printer', verbose_name='Printer')),
            ],
            options={
                'verbose_name': 'check',
                'verbose_name_plural': 'checks',
            },
        ),
    ]
